authors/urls.py
from django.urls import path
from authors import views

app_name = 'authors'

urlpatterns = [
    path(
        'register/',
        views.register_view,
        name='register'
    ),
    path(
        'register/create/',
        views.register_create,
        name='create'
    ),
    path(
        'login/',
        views.login_view,
        name='login'
    ),
    path(
        'login/authenticate/',
        views.login_create,
        name='authenticate'
    ),
    path(
        'logout/',
        views.logout_view,
        name='logout'
    ),
    path(
        'dashboard/',
        views.dashboard_view, name='dashboard'
    ),
    path(
        'dashboard/recipe/delete/',
        views.DashboardRecipeDelete.as_view(),
        name='dashboard_recipe_delete'
    ),
    path(
        'dashboard/recipe/create/',
        views.DashboardRecipe.as_view(),
        name='dashboard_recipe_create'
    ),
    path(
        'dashboard/recipe/<int:pk>/edit/',
        views.DashboardRecipe.as_view(),
        name='dashboard_recipe_edit'
    ),


]

project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('recipes.urls')),
    path("authors/", include('authors.urls')),
    path("__debug__/", include('debug_toolbar.urls'))
]

urlpatterns += \
    static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )  # type: ignore

recipes/urls.py
from . import views
from django.urls import path

app_name = 'recipes'

urlpatterns = [
    path("",
         views.RecipeListViewHome.as_view(), name="home"),
    path('recipes/search/',
         views.RecipeListViewSearch.as_view(), name="search"),
    path("recipes/category/<int:pk>/",
         views.RecipeListViewCategory.as_view(), name="category"),
    path("recipes/<int:pk>/",
         views.RecipeDetailView.as_view(), name="recipe"),
    path("recipes/api/v1/",
         views.RecipeListViewHomeApi.as_view(), name="recipes_api_v1"),
    path("recipes/api/v1/<int:pk>/",
         views.RecipeDetailApi.as_view(), name="recipes_api_v1_detail"),
]

authors/forms/login_form.py
from django import forms
from authors.utils.django_forms import add_placeholder  # type: ignore


class LoginForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_placeholder(self.fields['username'], 'Username...')
        add_placeholder(self.fields['password'], 'Password...')

    username = forms.CharField()
    password = forms.CharField(
        widget=forms.PasswordInput()
    )

authors/forms/register_form.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from authors.utils.django_forms import (add_placeholder, strong_password)


class RegisterForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_placeholder(self.fields['username'], 'Username...')
        add_placeholder(self.fields['email'], 'E-mail...')
        add_placeholder(self.fields['first_name'], 'Ex: John...')
        add_placeholder(self.fields['last_name'], 'Ex: Doe...')
        add_placeholder(self.fields['password'], 'Password...')
        add_placeholder(self.fields['password2'], 'Repeat your password...')

    username = forms.CharField(
        label='Username',
        help_text=('Ex: johndoe'),
        required=True,
        min_length=4,
        max_length=150,
        error_messages={
            'required': ('Username cannot be empty'),
            'min_length': ('Username must be at least 4 characters long'),
            'max_length': ('Username must be at most 150 characters long'),
        },
    )

    first_name = forms.CharField(
        required=True,
        label='First name',
        error_messages={'required': ('First name cannot be empty')},
    )

    last_name = forms.CharField(
        required=True,
        label='Last name',
        error_messages={'required': ('Last name cannot be empty')},
    )

    email = forms.EmailField(
        required=True,
        label='E-mail',
        help_text=('Ex: johndoe@email.com'),
        error_messages={'required': ('E-mail cannot be empty')},
    )

    password = forms.CharField(
        widget=forms.PasswordInput(),
        label='Password',
        error_messages={
            'required': ('Password cannot be empty'),
            'min_length': ('Password must be at least 8 characters long'),
            'max_length': ('Password must be at most 150 characters long'),
        },
        validators=[strong_password],
        min_length=8,
        max_length=150,
    )

    password2 = forms.CharField(
        widget=forms.PasswordInput(),
        label='Repeat Password',
        error_messages={
            'required': ('Please repeat your password')
        },
    )

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password',
            'password2',
        ]

    def clean_email(self):
        email = self.cleaned_data.get('email', '')
        exists = User.objects.filter(email=email).exists()

        if exists:
            self.add_error(
                'email',
                ValidationError(
                    ('Email is already in use'),
                    code='invalid'
                )
            )

        return email

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")  # type: ignore
        password2 = cleaned_data.get("password2")  # type: ignore

        if password and password2 and password != password2:
            self.add_error(
                None,
                ValidationError(
                    ('Passwords must be the same'),
                    code='invalid'
                )
            )

        return cleaned_data

base/templates/global/partials/_footer.html
<footer class="main-footer">
  <div class="developer">
    <a href="https://github.com/miguelcosta2c" target="_blank" rel="noreferrer noopener">
      <img src="https://avatars.githubusercontent.com/miguelcosta2c" alt="developer-image">
      By Miguel Costa
    </a>
  </div>
  <div class="powered">
    <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">
      Powered by Django
    </a>
  </div>
</footer>

base/templates/global/partials/_genericform.html
<div class="main-content container">
  {% if recipe %}
    <div class="form-content form-title center">
      <h2>{{ recipe.title }}</h2>
    </div>
  {% endif %}
  {% if messages %}
    <div class="form-content">
      {% include "global/partials/_message.html" %}
    </div>
  {% endif %}
  <form 
    class="form-container main-form" 
    action="{{ form_action }}" 
    method="POST"
    enctype="multipart/form-data"
  >
    {% csrf_token %}
    {% if form %}
      <div class="form-content form-content-grid">
        {% for field in form %}
          <div class="form-group {{ field.field.widget.attrs.class }}">
            <label for="{{ field.id_for_label }}">
              {{ field.label }}
            </label>
            {{ field }}
            {% if field.help_text %}
              <p class="help-text">
                {{ field.help_text }}
              </p>
            {% endif %}
            {{ field.errors }}
          </div>
          {% if field.name == 'cover' and field.value.url and recipe %}
            <div class="form-group span-2">
              <img 
                src="{{ field.value.url }}" 
                alt="Cover for {{ recipe.title }}"
              >
            </div>
          {% endif %}
        {% endfor %}
      </div>
    {% endif %}
    {% if form.non_field_errors %}
      <div class="form-content form-content-grid">
        <div class="form-group">
          {% for non_field_error in form.non_field_errors %}
            <div class="message message-error center">
              {{ non_field_error }}
            </div>
          {% endfor %}
        </div>
      </div>
    {% endif %}
    <div class="form-content form-content-grid">
      <div class="form-group">
        <button class="submit-button" type="submit">Save</button>
      </div>
    </div>
  </form>
</div>

base/templates/global/partials/_head.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/fontawesome.min.css" integrity="sha512-8Vtie9oRR62i7vkmVUISvuwOeipGv8Jd+Sur/ORKDD5JiLgTGeBSkI3ISOhc730VGvA5VVQPwKIKlmi+zMZ71w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/brands.min.css" integrity="sha512-bSncow0ApIhONbz+pNI52n0trz5fMWbgteHsonaPk42JbunIeM9ee+zTYAUP1eLPky5wP0XZ7MSLAPxKkwnlzw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/solid.min.css" integrity="sha512-6/gTF62BJ06BajySRzTm7i8N2ZZ6StspU9uVWDdoBiuuNu5rs1a8VwiJ7skCz2BcvhpipLKfFerXkuzs+npeKA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static "global/css/home.css" %}">

base/templates/global/partials/_header.html
<header class="main-header-container">
  <div class="header container">
    <h1 class="main-logo-title">
      <a class="main-logo" href="{% url "recipes:home" %}">
        <i class="fa-solid fa-utensils main-logo-icon"></i>
        <span class="main-logo-text">Recipes</span>
      </a>
    </h1>
  </div>
</header>

base/templates/global/partials/_loginform.html
<div class="main-content container">
  <div class="form-content form-title center">
    <h2>{{ form_title }}</h2>
    {% if request.user.is_authenticated %}
      <p>
        You are logged in with {{ request.user.username }}.
        <form action="{% url "authors:logout" %}" method="POST">
          {% csrf_token %}
          <input type="hidden" name="username" value="{{ request.user.username }}">
          <button class="generic-button" type="submit">
            Click here
          </button>
          to logout
        </form>
      </p>
    {% endif %}
  </div>
  {% if messages %}
    <div class="form-content">
      {% include "global/partials/_message.html" %}
    </div>
  {% endif %}
  <form class="form-container main-form" action="{{ form_action }}" method="POST">
    {% csrf_token %}
    {% if form %}
      <div class="form-content form-content-grid login-grid">
        {% for field in form %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}">
              {{ field.label }}
            </label>

            {{ field }}

            {% if field.help_text %}
              <p class="help-text">
                {{ field.help_text }}
              </p>
            {% endif %}

            {{ field.errors }}
          </div>
        {% endfor %}
      </div>
    {% endif %}
    {% if form.non_field_errors %}
      <div class="form-content form-content-grid">
        <div class="form-group">
          {% for non_field_error in form.non_field_errors %}
            <div class="message message-error center">
              {{ non_field_error }}
            </div>
          {% endfor %}
        </div>
      </div>
    {% endif %}
    <div class="form-content form-content-grid">
      <div class="form-group">
        <button class="submit-button" type="submit">{{ form_title }}</button>
      </div>
    </div>
  </form>
</div>

base/templates/global/partials/_loginmessage.html
{% if request.user.is_authenticated %}
  <div class="login-message">
    You are logged in with ({{ request.user.username }}).
    <form action="{% url "authors:logout" %}" method="POST">
      {% csrf_token %}
      <input type="hidden" name="username" value="{{ request.user.username }}">
      <button class="generic-button" type="submit">
        Click here
      </button>
      to logout
    </form>
    or
    <span class="dashboard-link">
      <a href="{% url "authors:dashboard" %}">
        see your Recipes
      </a>
    </span>
  </div>
{% endif %}

base/templates/global/partials/_message.html
{% if messages %}
  {% for message in messages %}
    <div class="message {{ message.tags }} center">
      {{ message }}
    </div>
  {% endfor %}
{% endif %}

base/templates/global/partials/_pagination.html
{% if recipes.has_other_pages %}
  <nav role="navigation" aria-label="Pagination" class="container pagination">
    <div class="pagination-content">
      {% if recipes.has_previous %}
        <a aria-label="Go to previous page {{ recipes.previous_page_number }}" 
          href="?page={{ recipes.previous_page_number }}{{ additional_url_query }}" 
          class="page-item page-link"
        >
          &lt;&lt;
        </a>
      {% endif %}
      {% if pagination_range.first_page_out_of_range %}
        <a aria-label="Go to page 1" class="page-link page-item" href="?page=1{{ additional_url_query }}">
          1
        </a>
        <span class="page-item">
          ...
        </span>
      {% endif %}
      {% for page in pagination_range.pagination %}
        {% if pagination_range.current_page == page %}
          <a aria-label="Current page {{ page }}" 
            class="page-link page-item page-current" 
            href="?page={{ page }}"
            aria-current="true"
          >
            {{ page }}
          </a>
        {% else %}
          <a aria-label="Go to page {{ page }}" class="page-link page-item" href="?page={{ page }}{{ additional_url_query }}">
            {{ page }}
          </a>
        {% endif %}
      {% endfor %}
      {% if pagination_range.last_page_out_of_range %}
        <span class="page-item">
          ...
        </span>
        <a aria-label="Go to page {{ pagination_range.total_pages }}" 
          class="page-link page-item" 
          href="?page={{ pagination_range.total_pages }}{{ additional_url_query }}"
        >
          {{ pagination_range.total_pages }}
        </a>
      {% endif %}
      {% if recipes.has_next %}
        <a aria-label="Go to next page {{ recipes.next_page_number }}" 
          href="?page={{ recipes.next_page_number }}{{ additional_url_query }}" 
          class="page-item page-link"
        >
          &gt;&gt;
        </a>
      {% endif %}
    </div>
  </nav>
{% endif %}

base/templates/global/partials/_registerform.html
<div class="main-content container">
  <form class="form-container" action="{{ form_action }}" method="POST">
    {% csrf_token %}
    <div class="form-content form-title center">
      <h2>{{ form_title }}</h2>
    </div>
    {% if messages %}
      <div class="form-group">
        {% include "global/partials/_message.html" %}
      </div>
    {% endif %}
    <div class="form-content form-content-grid">

      {% for field in form %}
        <div class="form-group">
          <label for="{{ field.id_for_label }}">
            {{ field.label }}
          </label>

          {{ field }}

          {% if field.help_text %}
            <p class="help-text">
              {{ field.help_text }}
            </p>
          {% endif %}

          {{ field.errors }}
        </div>
      {% endfor %}

    </div>

    {% if form.non_field_errors %}
      <div class="form-content form-content-grid">
        <div class="form-group">
          {% for non_field_error in form.non_field_errors %}
            <div class="message message-error center">
              {{ non_field_error }}
            </div>
          {% endfor %}
        </div>
      </div>
    {% endif %}

    <div class="form-content form-content-grid">
      <div class="form-group">
        <button class="submit-button" type="submit">{{ form_title }}</button>
      </div>
    </div>

  </form>
</div>

base/templates/global/partials/_search.html
<div class="search-container">
  <div class="container">
    <form action="{% url "recipes:search" %}" class="search-form">
      <input 
        type="search" 
        class="search-input" 
        name="q" 
        id="search-input"
        placeholder="Enter a recipe..."
        value="{{ search_term }}"
        required
      >
      <button type="submit" class="search-button">
        <i class="fas fa-search"></i>
      </button>
    </form>
  </div>
</div>